language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t nibblefritz/docker-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true nibblefritz/docker-react-test npm run test
